version: '3'

services:
  nginx-host:
    build: 777383/dof-exam_nginx:1.0
    ports:
    - "80:80"
    volumes: 
    - ./app:/site
    links:
    - php-host
    deploy: 
      mode: replicated
      replicas: 3
  php-host:
    image: 777383/dof-exam_php:1.0
    ports:
    - "9000:9000"
    volumes:
    - ./app:/site
    links:
    - redis-host
  redis-host:
    image: redis:latest
